name: docker-push

on:
  workflow_call:
    inputs:
      build-args:
        description: "docker build args (see --build-arg in docker docs)"
        default: ""
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: "dockerhub registry username"
        required: false
      DOCKERHUB_TOKEN:
        description: "dockerhub registry token"
        required: false

jobs:
  docker:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      -
        name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
      -
        name: set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: ${{ inputs.build-args }}
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
