name: docker-scan

on:
  workflow_call:
    inputs:
      build-args:
        description: "docker build args (see --build-arg in docker docs)"
        default: ""
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: build image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: ${{ inputs.build-args }}
          push: false
          tags: ${{ github.sha }}
      -
        name: trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ github.repository }}:${{ github.sha }}"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
