name: docker-scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: build image
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
      -
        name: trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ github.repository }}:${{ github.sha }}"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
