name: Go

on:
  workflow_call:
    secrets:
      PUBLIC_REPO_TOKEN:
        description: "public repo token, needed to push to brew tap"
        required: false

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: go releaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
