name: go-releaser

on:
  workflow_call:
    secrets:
      PUBLIC_REPO_TOKEN:
        description: "public repo token, needed to push to brew tap"
        required: false

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: go releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
