name: go-releaser

on:
  workflow_call:
    secrets:
      PUBLIC_REPO_TOKEN:
        description: "public repo token, needed to push to brew tap"
        required: false
    inputs:
      go-version:
        description: "go version"
        default: "1.23.1"
        required: false
        type: string
      krew:
        description: "whether to release to krew (project needs .krew.yaml file)"
        default: false
        required: false
        type: boolean

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
      -
        name: go version
        run: go version
      -
        name: go releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      -
        if: ${{ inputs.krew }}
        name: create crew file
        run: tag=${GITHUB_REF#refs/*/} version=${GITHUB_REF#refs/*/v} envsubst < .krew.tmpl.yaml > .krew.yaml
      -
        if: ${{ inputs.krew }}
        name: krew releaser
        uses: rajatjindal/krew-release-bot@v0.0.46
