name: Go

on:
  workflow_call:
    inputs:
      go-version:
        description: "go version"
        default: "1.19.4"
        required: false
        type: string
    secrets:
      PUBLIC_REPO_TOKEN:
        description: "public repo token, needed to push to brew tap"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version:  ${{ inputs.go-version }}
      - name: go test
        run: go test -v ./...
      - name: go vet
        run: go vet ./...
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
  release:
    needs:
      - test
      - scan
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: go releaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
